const fs = require('fs');
const path = require('path');

const files5bas = [
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 4 lis/octubre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__OCTUBRE__LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 4 lis/diciembre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__DICIEMBRE__LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 3 lis/septiembre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__SEPTIEMBRE_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 3 lis/agosto/LIMPIO/PLANIFICACION_CLASE_A_CLASE__AGOSTO_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 2 lis/junio/LIMPIO/PLANIFICACION_CLASE_A_CLASE__JUNIO__LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 2 lis/julio/LIMPIO/PLANIFICACION_CLASE_A_CLASE__JULIO__LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 1 lis/mayo/LIMPIO/PLANIFICACION_CLASE_A_CLASE__MAYO_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 1 lis/marzo/LIMPIO/PLANIFICACION_CLASE_A_CLASE__MARZO_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/unidad 1 lis/abril/LIMPIO/PLANIFICACION_CLASE_A_CLASE__ABRIL__LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/ASIGNATURAS 5 bas/TECNOLOGIA LIS/LIMPIO/PLANIFICACION_ANUAL_5TO_BASICO__TECNOLOGIA_58553_20200623_20150406_170015_LIMPIO_DRIVE.docx"
];

const files6bas = [
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 4/noviembre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__NOVIEMBRE_74197_20200709_20151101_213824_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 4/diciembre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__DICIEMBRE_74236_20200709_20151102_003101_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 3/septiembre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__SEPTIEMBRE_72471_20200709_20150825_174838_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 3/octubre/LIMPIO/PLANIFICACION_CLASE_A_CLASE__OCTUBRE_73372_20200709_20150924_224440_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 3/agosto/LIMPIO/PLANIFICACION_CLASE_A_CLASE__AGOSTO_61876_20200709_20150729_101621_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 2/junio/LIMPIO/PLANIFICACION_CLASE_A_CLASE__JUNIO_60651_20200709_20150602_152727_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 2/julio/LIMPIO/PLANIFICACION_CLASE_A_CLASE__JULIO_61265_20200709_20150630_192635_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 1/mayo/LIMPIO/PLANIFICACION_CLASE_A_CLASE__MAYO_59772_20200709_20150504_193207_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 1/marzo/LIMPIO/PLANIFICACION_CLASE_A_CLASE__MARZO_75975_20200709_20160126_143259_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/unidad 1/abril/LIMPIO/PLANIFICACION_CLASE_A_CLASE__ABRIL_58830_20200709_20150415_220408_LIMPIO_DRIVE.docx",
    "D:/Users/Pablo/Desktop/ESCRITORIO TRABAJO 2023/mi aula editado/SEGUNDO CICLO/SEXTO BASICO/ASIGNATURAS/VISUALES/LIMPIO/PLANIFICACION_ANUAL__ARTES_VISUALES_6TO._BASICO_58827_20200709_20150415_215437_LIMPIO_DRIVE.docx"
];

fs.writeFileSync(path.join(__dirname, 'published_5bas.json'), JSON.stringify(files5bas, null, 2));
fs.writeFileSync(path.join(__dirname, 'published_6bas.json'), JSON.stringify(files6bas, null, 2));
console.log('✅ Lists updated successfully');
